### ISSUE TITLE
Cannot resume the course after updating content Introduction/Chat/Create the app

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/kotlin-onboarding-introduction#110] opened 2023-03-04 10:36 UTC
While working on the course, I got a notification on updating the content. Before update I was at 16/34. However, after updating the content, it only shows the first course and cannot get back to 16.

**Comment by Geravant** [comment] 2023-03-06 15:27
The issue is [being fixed](https://youtrack.jetbrains.com/issue/EDU-5714/Folders-with-tasks-for-framework-lessons-are-deleted-not-correctly-after-updating-the-course-in-Student-mode) by the Jetbrain Academy team. I will update this as soon as there is a patch.

**Comment by nbirillo** [comment] 2023-04-17 13:03
Fixed in the [version#11](https://plugins.jetbrains.com/plugin/21067-kotlin-onboarding--introduction/versions/stable/321709) of the course

**Closed by nbirillo** 2023-04-17 13:03 UTC
Labels: bug, edu-plugin
